### ISSUE TITLE
[Bug]: level_zero backend failed with error: 39 (UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY) during training

### ISSUE THREAD

**Issue by desmondsow** [open-edge-platform/physical-ai-studio#440]
### Description

When training is initiated from web app, XPU OOM occurs.
```
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Enqueue process failed.
level_zero backend failed with error: 39 (UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY)
Fatal Python error: Aborted
```

Initial debug discovers this seems to only happens on PyTorch 2.10.++ version. Using older PyTorch 2.7.1 version with commit id (74f8ef72867df3f6f034c04568f64f27ce2e269c) seems to not have this issue.

### Steps to Reproduce

1. Change IMAGE_TAG to 0.1.0-dev-c96facf1 in .env
2. docker compose up -d
3. Record dataset and train
4. Observe XPU OOM

### Expected Behavior

Training should proceed normally.

### Actual Behavior

XPU OOM error

### Component

Library (VLA framework)

### Environment

```markdown
- OS: Ubuntu 24.04
- Kernel: 6.17.0-20-generic
```

### Logs / Error Output

```shell
2026-04-02 17:27:08.365 | INFO     | workers.base:run:143 - Starting TrainingWorker-14-60...
2026-04-02 17:27:08.393 | INFO     | workers.training_worker:run_loop:56 - Training Worker is running
2026-04-02 17:27:08.400 | INFO     | core.logging.utils:job_logging_ctx:108 - Started logging to /app/storage/logs/jobs/7e63bca9-808f-491d-bd61-83eccaa59729.log
2026-04-02 17:27:08.547 | INFO     | lerobot.datasets.video_utils:resolve_vcodec:106 - Using video codec: libsvtav1
2026-04-02 17:27:08.666 | INFO     | physicalai.data.datamodules:__init__:158 - DataLoader workers: 1
INFO: GPU available: False, used: False
2026-04-02 17:27:08.675 | INFO     | lightning_utilities.core.rank_zero:_info:61 - GPU available: False, used: False
INFO: TPU available: False, using: 0 TPU cores
2026-04-02 17:27:08.676 | INFO     | lightning_utilities.core.rank_zero:_info:61 - TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
2026-04-02 17:27:08.676 | INFO     | lightning_utilities.core.rank_zero:_info:61 - 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
2026-04-02 17:27:08.677 | INFO     | workers.base:run:187 - Starting Worker-60-thread
2026-04-02 17:27:08.700 | WARNING  | core.logging.handlers:write:47 - /app/application/backend/.venv/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:881: Checkpoint directory /app/storage/models/11bc2c16-f6b6-4b51-805c-38f5ba5e1477 exists and is not empty.
2026-04-02 17:27:08.836 | INFO     | core.logging.handlers:write:45 - Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /home/appuser/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
  0%|          | 0.00/44.7M [00:00<?, ?B/s]ogging.handlers:write:47 - 
  0%|          | 128k/44.7M [00:00<02:12, 352kB/s]handlers:write:47 - 
  1%|          | 256k/44.7M [00:00<02:10, 357kB/s]handlers:write:47 - 
  1%|          | 384k/44.7M [00:00<01:50, 421kB/s]handlers:write:47 - 
  1%|1         | 512k/44.7M [00:01<01:36, 478kB/s]handlers:write:47 - 
  1%|1         | 640k/44.7M [00:01<01:22, 557kB/s]handlers:write:47 - 
  2%|1         | 768k/44.7M [00:01<01:11, 646kB/s]handlers:write:47 - 
  2%|1         | 896k/44.7M [00:01<01:02, 729kB/s]handlers:write:47 - 
  2%|2         | 1.00M/44.7M [00:01<00:55, 818kB/s]andlers:write:47 - 
  3%|2         | 1.12M/44.7M [00:01<00:50, 912kB/s]andlers:write:47 - 
  3%|2         | 1.25M/44.7M [00:01<00:45, 1.01MB/s]ndlers:write:47 - 
  3%|3         | 1.50M/44.7M [00:02<00:38, 1.18MB/s]ndlers:write:47 - 
  4%|3         | 1.75M/44.7M [00:02<00:33, 1.34MB/s]ndlers:write:47 - 
  4%|4         | 2.00M/44.7M [00:02<00:29, 1.50MB/s]ndlers:write:47 - 
  5%|5         | 2.25M/44.7M [00:02<00:26, 1.66MB/s]ndlers:write:47 - 
  6%|5         | 2.50M/44.7M [00:02<00:24, 1.83MB/s]ndlers:write:47 - 
  6%|6         | 2.75M/44.7M [00:02<00:22, 1.97MB/s]ndlers:write:47 - 
  7%|6         | 3.12M/44.7M [00:02<00:19, 2.26MB/s]ndlers:write:47 - 
  8%|7         | 3.50M/44.7M [00:03<00:17, 2.47MB/s]ndlers:write:47 - 
  9%|8         | 3.88M/44.7M [00:03<00:16, 2.64MB/s]ndlers:write:47 - 
 10%|9         | 4.25M/44.7M [00:03<00:14, 2.85MB/s]ndlers:write:47 - 
 10%|#         | 4.62M/44.7M [00:03<00:14, 2.95MB/s]ndlers:write:47 - 
 11%|#1        | 5.12M/44.7M [00:03<00:12, 3.20MB/s]ndlers:write:47 - 
 12%|#2        | 5.50M/44.7M [00:03<00:12, 3.35MB/s]ndlers:write:47 - 
 14%|#3        | 6.12M/44.7M [00:03<00:10, 3.99MB/s]ndlers:write:47 - 
 15%|#5        | 6.75M/44.7M [00:03<00:08, 4.64MB/s]ndlers:write:47 - 
 16%|#6        | 7.25M/44.7M [00:03<00:08, 4.78MB/s]ndlers:write:47 - 
 19%|#8        | 8.38M/44.7M [00:04<00:05, 6.52MB/s]ndlers:write:47 - 
 20%|##        | 9.12M/44.7M [00:04<00:06, 5.42MB/s]ndlers:write:47 - 
 22%|##2       | 9.88M/44.7M [00:04<00:06, 5.26MB/s]ndlers:write:47 - 
 24%|##3       | 10.6M/44.7M [00:04<00:07, 4.61MB/s]ndlers:write:47 - 
 30%|##9       | 13.2M/44.7M [00:04<00:04, 7.66MB/s]ndlers:write:47 - 
 36%|###6      | 16.1M/44.7M [00:05<00:02, 10.4MB/s]ndlers:write:47 - 
 43%|####2     | 19.1M/44.7M [00:05<00:02, 9.56MB/s]ndlers:write:47 - 
 50%|####9     | 22.1M/44.7M [00:05<00:02, 11.5MB/s]ndlers:write:47 - 
 56%|#####6    | 25.1M/44.7M [00:05<00:01, 13.0MB/s]ndlers:write:47 - 
 63%|######2   | 28.1M/44.7M [00:06<00:01, 11.1MB/s]ndlers:write:47 - 
 70%|######9   | 31.1M/44.7M [00:06<00:01, 12.6MB/s]ndlers:write:47 - 
 77%|#######6  | 34.2M/44.7M [00:06<00:00, 13.9MB/s]ndlers:write:47 - 
 84%|########3 | 37.4M/44.7M [00:06<00:00, 11.9MB/s]ndlers:write:47 - 
 91%|######### | 40.6M/44.7M [00:07<00:00, 13.4MB/s]ndlers:write:47 - 
 98%|#########8| 43.9M/44.7M [00:07<00:00, 14.7MB/s]ndlers:write:47 - 
100%|##########| 44.7M/44.7M [00:07<00:00, 6.44MB/s]ndlers:write:47 - 
INFO: `weights_only` was not set, defaulting to `False`.
2026-04-02 17:27:17.258 | INFO     | lightning.pytorch.trainer.connectors.checkpoint_connector:dump_checkpoint:455 - `weights_only` was not set, defaulting to `False`.
2026-04-02 17:27:17.497 | WARNING  | core.logging.handlers:write:47 - /app/application/backend/.venv/lib/python3.12/site-packages/lightning/pytorch/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
2026-04-02 17:27:17.498 | WARNING  | core.logging.handlers:write:47 - /app/application/backend/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:429: Consider setting `persistent_workers=True` in 'train_dataloader' to speed up the dataloader worker initialization.
2026-04-02 17:27:17.760 | WARNING  | core.logging.handlers:write:47 - /app/application/backend/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
2026-04-02 17:27:17.761 | WARNING  | core.logging.handlers:write:47 - /app/application/backend/.venv/lib/python3.12/site-packages/lightning/pytorch/utilities/data.py:106: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention.
INFO:alembic.runtime.plugins:setup plugin alembic.autogenerate.schemas
INFO:alembic.runtime.plugins:setup plugin alembic.autogenerate.tables
INFO:alembic.runtime.plugins:setup plugin alembic.autogenerate.types
INFO:alembic.runtime.plugins:setup plugin alembic.autogenerate.constraints
INFO:alembic.runtime.plugins:setup plugin alembic.autogenerate.defaults
INFO:alembic.runtime.plugins:setup plugin alembic.autogenerate.comments
2026-04-02 17:27:22.625 | WARNING  | core.logging.handlers:write:47 - /app/application/backend/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:378: You have overridden `transfer_batch_to_device` in `LightningModule` but have passed in a `LightningDataModule`. It will use the implementation from `LightningModule` instance.
2026-04-02 17:27:23.324 | INFO     | uvicorn.protocols.http.httptools_impl:send:483 - 172.18.0.1:49540 - "GET /projects/11cbdd92-fa11-4a10-908c-a4e07c0f905f/models HTTP/1.1" 304
2026-04-02 17:27:23.328 | INFO     | api.job:jobs_websocket:90 - Except: disconnected!
2026-04-02 17:27:23.328 | INFO     | services.event_processor:unsubscribe:30 - unsubscribing
2026-04-02 17:27:23.328 | INFO     | api.job:jobs_websocket:93 - Jobs Websocket handling done...
2026-04-02 17:27:23.329 | INFO     | websockets.legacy.server:handler:263 - connection closed
2026-04-02 17:27:23.419 | INFO     | uvicorn.protocols.http.httptools_impl:send:483 - 172.18.0.1:49540 - "GET /api/projects HTTP/1.1" 200
2026-04-02 17:27:23.432 | INFO     | uvicorn.protocols.http.httptools_impl:send:483 - 172.18.0.1:49540 - "GET /api/projects/11cbdd92-fa11-4a10-908c-a4e07c0f905f HTTP/1.1" 200
2026-04-02 17:27:23.443 | INFO     | uvicorn.protocols.http.httptools_impl:send:483 - 172.18.0.1:49540 - "GET /api/projects/11cbdd92-fa11-4a10-908c-a4e07c0f905f/models HTTP/1.1" 200
2026-04-02 17:27:23.704 | INFO     | uvicorn.protocols.http.httptools_impl:send:483 - 172.18.0.1:49540 - "GET /api/jobs HTTP/1.1" 200
2026-04-02 17:27:23.713 | INFO     | uvicorn.protocols.websockets.websockets_impl:asgi_send:270 - 172.18.0.1:49558 - "WebSocket /api/jobs/ws" [accepted]
2026-04-02 17:27:23.713 | INFO     | services.event_processor:subscribe:24 - subscribing
2026-04-02 17:27:23.714 | INFO     | websockets.legacy.server:handshake:642 - connection open
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Enqueue process failed.
level_zero backend failed with error: 39 (UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY)
Fatal Python error: Aborted

Thread 0x0000772e231586c0 (most recent call first):
  File "/usr/local/lib/python3.12/threading.py", line 355 in wait
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 251 in _feed
  File "/usr/local/lib/python3.12/threading.py", line 1012 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772e170736c0 (most recent call first):
  File "/usr/local/lib/python3.12/threading.py", line 359 in wait
  File "/usr/local/lib/python3.12/threading.py", line 655 in wait
  File "/app/application/backend/.venv/lib/python3.12/site-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772e46ffd6c0 (most recent call first):
  File "/usr/local/lib/python3.12/selectors.py", line 468 in select
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1961 in _run_once
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 645 in run_forever
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 678 in run_until_complete
  File "/app/application/backend/src/workers/base.py", line 193 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772e81ffb6c0 (most recent call first):
  File "/usr/local/lib/python3.12/threading.py", line 359 in wait
  File "/usr/local/lib/python3.12/threading.py", line 655 in wait
  File "/app/application/backend/.venv/lib/python3.12/site-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772ea19386c0 (most recent call first):
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 395 in _recv
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 430 in _recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 216 in recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 387 in get
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_handler.py", line 300 in _queued_writer
  File "/usr/local/lib/python3.12/threading.py", line 1012 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772ea21396c0 (most recent call first):
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 395 in _recv
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 430 in _recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 216 in recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 387 in get
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_handler.py", line 300 in _queued_writer
  File "/usr/local/lib/python3.12/threading.py", line 1012 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772ea293a6c0 (most recent call first):
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 395 in _recv
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 430 in _recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 216 in recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 387 in get
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_handler.py", line 300 in _queued_writer
  File "/usr/local/lib/python3.12/threading.py", line 1012 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772ea313b6c0 (most recent call first):
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 395 in _recv
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 430 in _recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 216 in recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 387 in get
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_handler.py", line 300 in _queued_writer
  File "/usr/local/lib/python3.12/threading.py", line 1012 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772ea393c6c0 (most recent call first):
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 395 in _recv
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 430 in _recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 216 in recv_bytes
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 387 in get
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_handler.py", line 300 in _queued_writer
  File "/usr/local/lib/python3.12/threading.py", line 1012 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Thread 0x0000772eacda26c0 (most recent call first):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 90 in _worker
  File "/usr/local/lib/python3.12/threading.py", line 1012 in run
  File "/usr/local/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/usr/local/lib/python3.12/threading.py", line 1032 in _bootstrap

Current thread 0x0000773009920300 (most recent call first):
  File "/app/application/backend/.venv/lib/python3.12/site-packages/torch/_tensor_str.py", line 411 in get_summarized_data
  File "/app/application/backend/.venv/lib/python3.12/site-packages/torch/_tensor_str.py", line 411 in get_summarized_data
  File "/app/application/backend/.venv/lib/python3.12/site-packages/torch/_tensor_str.py", line 375 in _tensor_str
  File "/app/application/backend/.venv/lib/python3.12/site-packages/torch/_tensor_str.py", line 643 in _str_intern
  File "/app/application/backend/.venv/lib/python3.12/site-packages/torch/_tensor_str.py", line 724 in _str
  File "/app/application/backend/.venv/lib/python3.12/site-packages/torch/_tensor.py", line 573 in __repr__
  File "<string>", line 3 in __repr__
  File "/usr/local/lib/python3.12/dataclasses.py", line 262 in wrapper
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_better_exceptions.py", line 340 in _format_value
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_better_exceptions.py", line 288 in _get_relevant_values
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_better_exceptions.py", line 256 in _extract_frames
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_better_exceptions.py", line 454 in _format_exception
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_better_exceptions.py", line 422 in _format_exception
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_better_exceptions.py", line 422 in _format_exception
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_better_exceptions.py", line 573 in format_exception
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_handler.py", line 147 in emit
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_logger.py", line 2066 in _log
  File "/app/application/backend/.venv/lib/python3.12/site-packages/loguru/_logger.py", line 2099 in exception
  File "/app/application/backend/src/workers/training_worker.py", line 170 in _train_model
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88 in _run
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1999 in _run_once
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 645 in run_forever
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 678 in run_until_complete
  File "/app/application/backend/src/workers/base.py", line 150 in run
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314 in _bootstrap
  File "/usr/local/lib/python3.12/multiprocessing/spawn.py", line 135 in _main
  File "/usr/local/lib/python3.12/multiprocessing/spawn.py", line 122 in spawn_main
  File "<string>", line 1 in <module>

Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, _cyutility, scipy._cyutility, scipy._lib._ccallback_c, yaml._yaml, numba.core.typeconv._typeconv, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._pcg64, numpy.random._generator, numpy.random._mt19937, numpy.random._philox, numpy.random._sfc64, numpy.random.mtrand, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, PIL._imaging, sqlalchemy.cyextension.collections, sqlalchemy.cyextension.immutabledict, sqlalchemy.cyextension.processors, sqlalchemy.cyextension.resultproxy, sqlalchemy.cyextension.util, greenlet._greenlet, markupsafe._speedups, pyarrow.lib, pandas._libs._cyutility, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.properties, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, pyarrow._acero, pyarrow._fs, pyarrow._csv, pyarrow._json, pyarrow._substrait, pyarrow._dataset, pyarrow._dataset_orc, pyarrow._parquet, pyarrow._azurefs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, pyarrow._parquet_encryption, pyarrow._dataset_parquet_encryption, pyarrow._dataset_parquet, charset_normalizer.md, charset_normalizer.cd, requests.packages.charset_normalizer.md, requests.packages.chardet.md, requests.packages.charset_normalizer.cd, requests.packages.chardet.cd, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket.mask, aiohttp._websocket.reader_c, frozenlist._frozenlist, xxhash._xxhash, PIL._imagingft, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.error, av.dictionary, av.container.pyio, av.utils, av.option, av.descriptor, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.opaque, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.hwaccel, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.filter.loudnorm, av.audio.resampler, av.audio.codeccontext, av.audio.fifo, av.bitstream, av.video.codeccontext, regex._regex, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._batched_linalg, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_schur_sqrtm, scipy.linalg._matfuncs_expm, scipy.linalg._linalg_pythran, scipy.linalg.cython_blas, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpacklib, scipy.sparse.linalg._propack, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._slsqplib, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy._lib._uarray._uarray, scipy.special._ufuncs_cxx, scipy.special._ellip_harm_2, scipy.special._special_ufuncs, scipy.special._gufuncs, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._decomp_interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._hausdorff, scipy.spatial._distance_wrap, scipy.spatial.transform._rotation_cy, scipy.spatial.transform._rigid_transform_cy, scipy.optimize._direct, psutil._psutil_linux, scipy.signal._sigtools, scipy.signal._max_len_seq_inner, scipy.signal._upfirdn_apply, scipy.signal._spline, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._dierckx, scipy.interpolate._ppoly, scipy.interpolate._interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.ndimage._nd_image, scipy.ndimage._rank_filter_1d, _ni_label, scipy.ndimage._ni_label, scipy.signal._sosfilt, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.special.cython_special, scipy.stats._stats, scipy.stats._biasedurn, scipy.stats._stats_pythran, scipy.stats._levy_stable.levyst, scipy.stats._ansari_swilk_statistics, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._rcont.rcont, scipy.stats._qmvnt_cy, scipy.signal._peak_finding_utils, google._upb._message, scipy.fftpack.convolve, scipy.io.matlab._mio_utils, scipy.io.matlab._streams, scipy.io.matlab._mio5_utils (total: 252)
```

**Comment by desmondsow** [comment]
Hi @MarkRedeman, I tried ACT with lowest batch size and data workers to 1. It didn't work as well on latest version. 

Initial debug discovers this seems to only happens on PyTorch 2.10.++ version. Using older PyTorch 2.7.1 version with commit id (https://github.com/open-edge-platform/physical-ai-studio/commit/74f8ef72867df3f6f034c04568f64f27ce2e269c) seems to not have this issue. All lower deps., libze1 etc, are same.

**Comment by MarkRedeman** [comment]
I currently only have a lunar lake device (Core Ultra 7 258V) to test this on so it's a bit hard to figure out what's wrong.
So far I've found that both on the latest main as well as `IMAGE_TAG=0.1.0-dev-c96facf1` are working for me when using docker.
However when I enable auto batch size the whole thing crashes when it tries to use a batch size of 32.

I'm also trying to check this using python directly without docker, but there I do seem to get an out of memory error even when using batch size of 1.
